comment: off
coverage:
  status:
    project:
      default: true  # disable the default status that measures entire project
      tests:  # declare a new status context "tests"
        target: 100%  # we always want 100% coverage here
        paths: "codespell_lib/tests/"  # only include coverage in "tests/" folder
      app:  # declare a new status context "app"
        paths: "!codespell_lib/tests/"  # remove all files in "tests/"
