[tox]
min_version = 4.22
env_list = unitest,type,dictionaries

[testenv:dictionaries]
description = run dictionary checks
skip_install = true
allowlist_externals = make
commands = make check-dictionaries

[testenv:unitest]
description = run unit tests
dependency_groups = dev
commands = pytest --cov=codespell_lib codespell_lib

[testenv:type]
description = run type checks
dependency_groups = types
commands = mypy codespell_lib
